First Implement
approvers/devoirs pull request #6
Opened 2020-05-20 14:30 UTC by Siketyan

2020-05-20 14:32 UTC, Siketyan commented
適当に Reviewer 振ったので暇な方レビューお願いします 🙏

2020-05-21 01:24 UTC, MikuroXina requested changes
とりあえず Request changes 第一弾
あとで設計の方面からもう一回送る予定です

2020-05-21 01:24 UTC, MikuroXina commented on src/services/api/base.ts
> +          .end();
```suggestion
      const callback = (resolve, reject) => (response) => {
      let data = '';

      if (response.statusCode === 401) {
        resolve(this.request(method, path, true));
        return;
      }
      if (response.statusCode !== 200) {
        reject(response);
        return;
      }

      response.on('data', (chunk) => (data += chunk));
      response.on('end', () => {
        resolve(JSON.parse(data)['value'] as T);
      });
    };

    return new Promise((resolve, reject) =>
      request(url, options, callback(resolve, reject))
        .on('error', (error) => {
          throw error;
        })
        .end()
    );
```

2020-05-21 01:24 UTC, MikuroXina commented on src/services/api/base.ts
> +      (async () => {
```suggestion
  protected async request<T>(method: string, path: string, refreshToken: boolean = false): Promise<T> {
```
これでいいのだ

2020-05-21 01:24 UTC, MikuroXina commented on src/utilities/async-or-sync.ts
> +      resolve(fSync?.call(thisArg, ...args));
これをやったとしても、同期関数は他の処理をブロックするので意味がない気がする

2020-05-21 01:24 UTC, MikuroXina commented on src/services/token/provider/index.ts
> +}
同期関数と非同期関数の両方を用意する意図がよくわからない
非同期関数版だけで十分だと思う

2020-05-21 01:24 UTC, MikuroXina commented on src/services/token-storage/index.ts
> +}
格納/読み出しとか遅い処理なのに、非同期関数じゃないのが気になる

2020-05-21 01:24 UTC, MikuroXina commented on src/services/api/base.ts
> +    return new Promise<T>(((resolve, reject) => {
```suggestion
    return new Promise<T>((resolve, reject) => {
```
`(` と `)` が一つずつ余計

2020-05-21 01:26 UTC, Siketyan commented on src/models/assignment.ts
> +  assignedDateTime: Date;
ぼくもわからない（API にあったので）

2020-05-21 01:37 UTC, MikuroXina requested changes

2020-05-21 01:37 UTC, MikuroXina commented on src/services/api/base.ts
> +        } else if (response.statusCode !== 200) {
```suggestion
        } if (response.statusCode !== 200) {
```
`return else` 警察だ!

2020-05-21 01:42 UTC, Siketyan commented on src/services/api/base.ts
> +        } else if (response.statusCode !== 200) {
生きててごめんなさい

2020-05-21 01:54 UTC, MikuroXina requested changes

2020-05-21 01:54 UTC, MikuroXina commented on src/services/token-storage/filesystem.ts
> +  }
```suggestion
  async load(): Promise<string> {
    const fileStat = await stat(this.path);
    if (!fileStat.isFile()) {
      throw new Error('invalid storage path');
    }
    return await readFile(this.path, {
      encoding: this.encoding,
    });
  }
```
こうかなぁ (`stat` は `import` してね)

2020-05-21 02:05 UTC, Siketyan commented on src/services/token-storage/filesystem.ts
> +  }
タスカル（めんどすぎて Promise で書きそうになった）

2020-05-21 02:18 UTC, MikuroXina requested changes

2020-05-21 02:18 UTC, MikuroXina commented on src/services/token-storage/filesystem.ts
> +    return await this.exists() ? null : await readFile(this.path, {
`Promise<string>` が戻り値型なのに `null` を返している理由が分からない
(できる限り不正な値を外に漏らしたくないので、存在しないなら `throw` してほしい)

2020-05-21 02:24 UTC, MikuroXina commented on src/services/token-storage/filesystem.ts
> +    return await this.exists() ? null : await readFile(this.path, {
Resolve する前に理由を書いてくれー
あとこれだと戻り値型は `Promise<string | null>` じゃないとおかしいんじゃー

2020-05-21 02:30 UTC, kawaemon commented on src/services/api/base.ts
> +  protected async request<T>(method: string, path: string, refreshToken: boolean = false): Promise<T> {
```suggestion
  //type Method = "POST" | "GET" | .... 
  protected async request<T>(method: Method, path: string, refreshToken: boolean = false): Promise<T> {
```

method用のTypeを作っても良いかもしれない？

2020-05-21 02:31 UTC, Siketyan commented on src/services/api/base.ts
> +  protected async request<T>(method: string, path: string, refreshToken: boolean = false): Promise<T> {
正しい（突貫工事をゆるして）

2020-05-21 02:39 UTC, Siketyan commented on src/services/token-storage/filesystem.ts
> +    return await this.exists() ? null : await readFile(this.path, {
@MikuroXina throw に変えたので resolve しちゃった

2020-05-21 02:40 UTC, MikuroXina commented on src/services/token-storage/filesystem.ts
> +    return await this.exists() ? null : await readFile(this.path, {
なんかそのコミットが GitHub に表示されてなかった、了解

2020-05-21 02:42 UTC, kawaemon approved these changes
***† SUPER CLEAN CODE †***

2020-05-21 03:06 UTC, MikuroXina requested changes
こんな感じっすかね

2020-05-21 03:06 UTC, MikuroXina commented on src/services/authorizer.ts
> +        }
レスポンスがおかしかったりヘッダや `hash` のアクセスに失敗したりしたときに `reject` するようにしないと異常が検知できず後続の非同期処理もできないと思う

2020-05-21 09:06 UTC, Siketyan commented
🤔 

```console
Error: Cannot find module 'fs/promises'
Require stack:
- C:\Users\Siketyan\Projects\approvers\devoirs\src\services\token-storage\filesystem.ts
- C:\Users\Siketyan\Projects\approvers\devoirs\src\main.ts
```

2020-05-21 09:19 UTC, MikuroXina commented
```
import { promises } from "fs";
const { readFile } = promises;
```
みたいな感じでいけるはずです

2020-05-21 09:37 UTC, MikuroXina requested changes

2020-05-21 09:37 UTC, MikuroXina commented on src/services/api/base.ts
> +    ));
```suggestion
    const token = await (
       refreshToken ? this.tokenProvider.refresh() : this.tokenProvider.get()
    );
```
カッコが多いっす
フォーマッタ入れてたらこういうことにはならんのでおすすめ

2020-05-21 09:40 UTC, Siketyan commented on src/services/api/base.ts
> +    ));
死にます………
次の PR で ESLint + Prettier 導入します……

2020-05-21 09:49 UTC, MikuroXina commented on src/services/api/client.ts
> +  }
26b06b5 での対応を確認

2020-05-21 14:43 UTC, MikuroXina approved these changes
よく頑張った、えらい

2020-05-21 14:44 UTC, merged